name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run with Gradle
        run: ./gradlew build

      - name: Run Gradle build
        run: ./gradlew build dokkaHtml

      - name: Archive Dokka HTML output
        uses: actions/upload-artifact@v4
        with:
          name: dokka-html
          path: docs/kdoc

  docker:
    runs-on: ubuntu-latest
    steps:
      #      - name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.actor }}
      #          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: jarrid/keyper:latest

  mkdocs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Dokka HTML output
        uses: actions/download-artifact@v4
        with:
          name: dokka-html
          path: docs/kdoc
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install "mkdocs-material[imaging]"
      - run: mkdocs build